[package]
name = "RustMap"
version = "0.1.0"
authors = ["luanngominh <luannm2@vng.com.vn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
