[package]
name = "RustMap"
version = "0.1.0"
authors = ["luanngominh <ngominhluanbox@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.15"
log = "0.4.11"
colored = "2.0.0"
rlimit = "0.3.0"